#!/usr/bin/env bash

THIN_W=1920
THIN_H=200
WIDE_W=450
WIDE_H=1080
TOLERANCE=10

SCRIPT_DIR="$HOME/.local/share/mc-resizer"
SCRIPT_FILE="$SCRIPT_DIR/resize.js"

mkdir -p "$SCRIPT_DIR"
cat > "$SCRIPT_FILE" << EOF
(function() {
    var THIN_W = $THIN_W;
    var THIN_H = $THIN_H;
    var WIDE_W = $WIDE_W;
    var WIDE_H = $WIDE_H;
    var TOL = $TOLERANCE;

    var clients = workspace.windowList();
    var mc = null;
    for (var i = 0; i < clients.length; i++) {
        var cap = clients[i].caption || "";
        if (cap.match(/Minecraft\\*|MCSR/)) {
            mc = clients[i];
            break;
        }
    }
    if (!mc) return;

    var screen = workspace.virtualScreenSize;
    var screenW = screen.width;
    var screenH = screen.height;

    var isFS = mc.fullScreen;
    var curW = mc.frameGeometry.width;
    var curH = mc.frameGeometry.height;

    function near(a, b) {
        return Math.abs(a - b) <= TOL;
    }

    function centerWindow(w, h) {
        mc.fullScreen = false;
        mc.frameGeometry = {
            x: Math.round((screenW - w) / 2),
            y: Math.round((screenH - h) / 2),
            width: w,
            height: h
        };
    }

    if (isFS) {
        centerWindow(THIN_W, THIN_H);
    } else if (near(curW, THIN_W) && near(curH, THIN_H)) {
        centerWindow(WIDE_W, WIDE_H);
    } else if (near(curW, WIDE_W) && near(curH, WIDE_H)) {
        mc.fullScreen = true;
    } else {
        mc.fullScreen = true;
    }
})();
EOF

qdbus6 org.kde.KWin /Scripting org.kde.kwin.Scripting.unloadScript mc-resizer 2>/dev/null
qdbus6 org.kde.KWin /Scripting org.kde.kwin.Scripting.loadScript "$SCRIPT_FILE" mc-resizer >/dev/null
qdbus6 org.kde.KWin /Scripting org.kde.kwin.Scripting.start
qdbus6 org.kde.KWin /Scripting org.kde.kwin.Scripting.unloadScript mc-resizer 2>/dev/null
